USE LOCADORA;
GO

SELECT * FROM EMPRESA

SELECT * FROM MARCA

SELECT * FROM MODELO

SELECT * FROM EMPRESA

SELECT * FROM VEICULO

SELECT * FROM CLIENTE

SELECT * FROM ALUGUEL

--MOSTRA TODAS AS INFORMAÇÕES PARA UM ALUGUEL

SELECT preco, Adata, nome, RG, nomeModelo, nomeMarca, placa, nomeEmpresa, endereco FROM ALUGUEL
LEFT JOIN CLIENTE
ON ALUGUEL.idCliente = CLIENTE.idCliente
LEFT JOIN VEICULO
ON ALUGUEL.idVeiculo = VEICULO.idVeiculo
LEFT JOIN MODELO
ON MODELO.idModelo = VEICULO.idModelo
LEFT JOIN MARCA 
ON MARCA.idMarca = MODELO.idMarca
LEFT JOIN EMPRESA
ON EMPRESA.idEmpresa = VEICULO.idEmpresa;

--TODOS OS DADOS DE UM VEICULO

SELECT nomeModelo, nomeMarca, placa FROM VEICULO
LEFT JOIN MODELO
ON VEICULO.idModelo = MODELO.idModelo
LEFT JOIN MARCA
ON MODELO.idMarca = MARCA.idMarca;