USE CATALOGO
GO

INSERT INTO GENERO(nomeGenero)
VALUES ('AÇÃO'), ('TERROR'), ('COMÉDIA'), ('ROMANCE')
GO

INSERT INTO FILME( idGenero, tituloFilme)
VALUES (1, 'VINGADORES: ULTIMATO'), (1, 'PANTERA NEGRA'), 
(3, 'GENTE GRANDE'), (3, 'MINHA MÃE É UMA PEÇA'),
(2, 'INVOCAÇÃO DO MAL'), (2, 'AIVIDADE PARANORMAL')
GO
