CREATE DATABASE UNIDAS;
GO

USE UNIDAS;
GO

CREATE TABLE PESSOA(
	idPessoa INT PRIMARY KEY IDENTITY(1,1),
	nomePessoa VARCHAR(20) NOT NULL UNIQUE
);

CREATE TABLE TELEFONE(
	idTelefone INT PRIMARY KEY IDENTITY(1,1),
	idPessoa INT FOREIGN KEY REFERENCES PESSOA(idPessoa),
	numeroTelefone CHAR(11) NOT NULL
);
GO

CREATE TABLE EMAIL(
	idEmail INT PRIMARY KEY IDENTITY(1,1),
	idPessoa INT FOREIGN KEY REFERENCES PESSOA(idPessoa),
	endEmail VARCHAR(256) NOT NULL UNIQUE
);
GO

CREATE TABLE CNH(
	idCNH INT PRIMARY KEY IDENTITY(1,1),
	idPessoa INT FOREIGN KEY REFERENCES PESSOA(idPessoa),
	decricao CHAR(11) NOT NULL UNIQUE
);
GO

INSERT INTO PESSOA (nomePessoa)
VALUES('MARCOS'), ('MATHEUS')

SELECT * FROM PESSOA

INSERT INTO TELEFONE (idPessoa, numeroTelefone)
VALUES (1, '9999'), (1, '8888'), (2, '9999')
GO

SELECT * FROM TELEFONE

INSERT INTO EMAIL (idPessoa, endEmail)
VALUES(1, 'm.santos@gmail.com'),
(2, 'm.machado@gmail.com')
GO

SELECT * FROM EMAIL

INSERT INTO CNH (idPessoa, decricao)
VALUES (1, '1234'), (2, '4334')
GO

SELECT * FROM CNH